//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Voertuigen_Verhuur_JansenEntities : DbContext
    {
        public Voertuigen_Verhuur_JansenEntities()
            : base("name=Voertuigen_Verhuur_JansenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caterie> Cateries { get; set; }
        public virtual DbSet<Klanten> Klantens { get; set; }
        public virtual DbSet<Medewerker> Medewerkers { get; set; }
        public virtual DbSet<PrijsHistorie> PrijsHistories { get; set; }
        public virtual DbSet<Verhuren> Verhurens { get; set; }
        public virtual DbSet<Voertuigen> Voertuigens { get; set; }
    }
}
